### ISSUE TITLE
RGW doesn't work

### ISSUE THREAD

**Issue by agareev** [ceph/ceph-helm#52]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
This is a BUG REPORT

**Version of Helm and Kubernetes**:
k8s - 1.8.7
helm - v2.8.2

**Which chart**:
ceph

**What happened**:
rgw container doesnt work.
it writes a log
```
Initialization timeout, failed to initialize
```

**What you expected to happen**:
rgw works and binds port 8088

**How to reproduce it** (as minimally and precisely as possible):
just run 
```
helm install --name=ceph local/ceph --namespace=ceph -f ./ceph-overrides.yaml
```

**Anything else we need to know**:

**Comment by feresberbeche** [comment]
Actually I got it figured out, the "ceph -s" in the mon pod must return HEALTH_OK if it dosen't the rgw pod will never start properly.
I was installing everything in a single node so I had to add 
```
conf:
  ceph:
    config:
      global:
        osd_pool_default_size: 1
      osd:
        osd_crush_chooseleaf_type: 0
```

to the ceph-overrides.yaml to make the health okay with a single storage device on a single node.
